MONGODB_HOST: mongodb-{{ env }}.daws-90.shop
REDIS_HOST: redis-{{ env }}.daws-90.shop
MYSQL_HOST: mysql-{{ env }}.daws-90.shop 
RABBITMQ_HOST: rabbitmq-{{ env }}.daws-90.shop 
CATALOGUE_HOST: catalogue-{{ env }}.daws-90.shop
USER_HOST: user-{{ env }}.daws-90.shop
CART_HOST: cart-{{ env }}.daws-90.shop
SHIPPING_HOST: shipping-{{ env }}.daws-90.shop
PAYMENT_HOST: payment-{{ env }}.daws-90.shop